config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "videos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :video
  belongs_to :user

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :videos
  has_many :comments
  
  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
  end
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :file, FileUploader
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments

  with_options presence: true do
    validates :title
    validates :description
    validates :file
    validates :image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action  :authenticate_user!
  def create
    comment = Comment.create(comment_params)
    redirect_to "/videos/#{comment.video.id}"
  end
  def destroy
    Comment.find_by(id: params[:id], video_id: params[:video_id]).destroy
    redirect_back(fallback_location: root_path) 
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, video_id: params[:video_id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :destory, :update]
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    @videos = @videos.where("title LIKE ?", "%#{params[:q]}%") if params[:q].present?
    @videos = @videos.page(params[:page]).per(6)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video.increment!(:view_count)
    @comment = Comment.new
    @comments = @video.comments.includes(:user)
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user = current_user

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :file, :image)
    end

    def check_owner
      redirect_to root_path unless @video.user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/create.js.erb
$("#comments").html("<%= j(render("videos/comments")) %>")

app/views/comments/destory.js.erb
$("#comments").html("<%= j(render("videos/comments")) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videotube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <a href="./" class="navbar-brand">
        <%= fa_icon "youtube-play", class: "text-danger mr-1" %>
        VideoTube
      </a>

      <%= form_tag videos_path, method: :get, class: "form-inline" do %>
        <%= text_field_tag :q, params[:q], class: "form-control mr-2" %>
        <%= submit_tag "検索", class: "btn btn-danger" %>
      <% end %>

      <div>
        <% if current_user %>
          <%= link_to "投稿", new_video_path, class: "btn btn-danger"  %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-danger" %>
          <%= link_to "会員登録", new_user_registration_path, class: "btn btn-danger" %>
        <% end %>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="card">
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
  <br>
</html>

app/views/videos/_comments.html.erb
<div>
  <% if @comments %>
    <% @comments.each do |comment| %>
        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
        <%= comment.text %>
    <div class="text-black-50">
      <span class="font-italic"><%= time_ago_in_words comment.created_at %></span>
    　　 <%= link_to "削除", video_comment_path(comment.video.id, comment.id), remote: true, method: :delete, data: {confirm: "削除しますか？"} if current_user && (current_user == comment.user) %><br><br>
    </div>
    <% end %>
  <% end %> 
</div>

<div class="form-group">
  <% if current_user %>
    <%= form_with(model: [@video, @comment], local: true) do |form| %>
      <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "form-control mb-2"%>
      <%= form.submit "コメント", class: "btn btn-danger" %>
    <% end %>
  <% else %>
    <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
  <% end %>
</div>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :file %>
    <%= form.file_field :file, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  
  <div class="actions">
    <%= form.submit "投稿", class: "btn btn-danger"%>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div class="col-4 mb-3">
  <div class="card">
  <%= image_tag video.image.url, class: "w-100" if video.image? %>
    <div class="card-body">
    <%= link_to video, class: "text-dark" do %>
      <strong>
      <%= video.title %>
      </strong>
      <p class="small">
        <%= truncate video.description, length: 30 %>
     
        <div class="count_display text-gray small">
          <div class="created1">
        <%= time_ago_in_words video.created_at %>
          </div>
          <div class="count1">
        count <%= video.view_count.to_i %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="row">
<%= render @videos %>
</div>
<%= paginate @videos %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<%= video_tag @video.file.url, controls: true, class: "w-100" if @video.file? %>
<h4><%= @video.title %>
</h4>
<br>
投稿者:　<%= @video.user.nickname %>
<%= simple_format @video.description %>
View count:　<%= @video.view_count.to_i %>
</p>
<% if current_user && (@video.user == current_user) %>
<%= link_to '編集', edit_video_path(@video), class: "btn btn-danger" %> |
<%= link_to '削除', @video, method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-outline-danger" %> |
<%= link_to '一覧', videos_path, class: "btn btn-danger" %>
<% else %>
<%= link_to '一覧', videos_path, class: "btn btn-danger" %>
<% end %>
<br><br><br>

<div id="comments">
  <%= render "videos/comments" %>
</div>